### ISSUE TITLE
Options are not passed to socket-io

### ISSUE THREAD

**Issue by jamesholcomb** [feathersjs/socketio#101]
According to the docs, options can be passed to engine-io

_app.configure(socketio(options [, callback]))_

_Sets up the Socket.io transport with the [given Socket.io options object](https://github.com/socketio/engine.io#methods-1) and optionally calls the callback described above._

### Steps to reproduce
````js
const socketio = require("feathers-socketio")
const feathers = require("feathers")
const app = feathers()
app.configure(socketio({ pingTimeout: 500 }, (io) => { })
````
### Expected behavior
Options should be passed to engine-io

### Actual behavior
Options are not passed (pingTimeout is still default 60000)

````
engine handshaking client "Pc2Haio7MvD9rkT5AAAA" +0ms
engine:socket sending packet "open" ({"sid":"Pc2Haio7MvD9rkT5AAAA","upgrades":[],"pingInterval":25000,"pingTimeout":60000}) +2ms
engine:socket flushing buffer to transport +0ms
engine:ws writing "0{"sid":"Pc2Haio7MvD9rkT5AAAA","upgrades":[],"pingInterval":25000,"pingTimeout":60000}" +0ms
````

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
feathers-socketio 2.0.1

**NodeJS version**:
8.9
**Operating System**:
MacOS
**Browser Version**:

**React Native Version**:
0.46.4
**Module Loader**:

**Comment by daffl** [comment]
Setting options is being tested in https://github.com/feathersjs/socketio/blob/158e067aff7e5597d281c4bc1f5231d2b1bffb29/test/index.test.js#L91, I'm not sure where the issue might be at the moment.

**Comment by jamesholcomb** [comment]
False alarm...was due to a bad import which set pingInterval to undefined.
