### ISSUE TITLE
How to stop listening to socket server from client service 

### ISSUE THREAD

**Issue by gkumar9** [feathersjs/socketio#103]

**Comment by daffl** [comment]
One way would be to just disconnect from the socket. What specifically are you trying to accomplish?

**Comment by gkumar9** [comment]
![screenshot from 2017-12-12 10-14-29](https://user-images.githubusercontent.com/33317261/33867878-772603f8-df25-11e7-9bdb-9aab07f1b2e9.jpg)

This keeps coming in my console

```
  import feathers from 'feathers/client';
  import socketio from 'feathers-socketio/client';
  import io from 'socket.io-client';
```

**Comment by daffl** [comment]
Is socketserver.com actually a valid domain that your server is running on?

**Comment by gkumar9** [comment]
@daffl  No its a demo server.i once tested with that link. But then i removed it from the code .But still its giving error. It seems if socket is connected then we have to forcefully disconnect . But I don't know how to disconnect it .

**Comment by daffl** [comment]
What about `socket.disconnect()`?
