### ISSUE TITLE
How to change 5000ms timeout? 

### ISSUE THREAD

**Issue by vodniciarv** [feathersjs/socketio#107]
Hello,
I have this error:
![screenshot_3](https://user-images.githubusercontent.com/14403446/35049141-bb133150-fba7-11e7-9a96-b6687910e806.png)
And I want to change 5000ms to 15000ms (for example).
How to do it?

**Comment by daffl** [comment]
Setting the timeout is [documented here](https://docs.feathersjs.com/api/client/socketio.html#socketiosocket-options).

If you [upgrade to the latest version](https://docs.feathersjs.com/migrating.html) you will also probably get a more meaningful error message (unless the method actually takes longer than 5 seconds to complete).

**Comment by vodniciarv** [comment]
thank's
I wrote all the code on the server, but I needed it in the browser.
My mistake
